// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wtime.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_wtime_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_wtime_2eproto

#include <limits>
#include "internal/times_internal.h"

#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3013000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3013000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/wrappers.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_wtime_2eproto TIMES_API
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TIMES_API TableStruct_wtime_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern TIMES_API const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_wtime_2eproto;
namespace HSS {
namespace Times {
class WTime;
class WTimeDefaultTypeInternal;
TIMES_API extern WTimeDefaultTypeInternal _WTime_default_instance_;
class WTimeSpan;
class WTimeSpanDefaultTypeInternal;
TIMES_API extern WTimeSpanDefaultTypeInternal _WTimeSpan_default_instance_;
class WTimeZone;
class WTimeZoneDefaultTypeInternal;
TIMES_API extern WTimeZoneDefaultTypeInternal _WTimeZone_default_instance_;
class WTimeZone_TZTimeZone;
class WTimeZone_TZTimeZoneDefaultTypeInternal;
TIMES_API extern WTimeZone_TZTimeZoneDefaultTypeInternal _WTimeZone_TZTimeZone_default_instance_;
class WTimeZone_WTZDetails;
class WTimeZone_WTZDetailsDefaultTypeInternal;
TIMES_API extern WTimeZone_WTZDetailsDefaultTypeInternal _WTimeZone_WTZDetails_default_instance_;
}  // namespace Times
}  // namespace HSS
PROTOBUF_NAMESPACE_OPEN
template<> TIMES_API ::HSS::Times::WTime* Arena::CreateMaybeMessage<::HSS::Times::WTime>(Arena*);
template<> TIMES_API ::HSS::Times::WTimeSpan* Arena::CreateMaybeMessage<::HSS::Times::WTimeSpan>(Arena*);
template<> TIMES_API ::HSS::Times::WTimeZone* Arena::CreateMaybeMessage<::HSS::Times::WTimeZone>(Arena*);
template<> TIMES_API ::HSS::Times::WTimeZone_TZTimeZone* Arena::CreateMaybeMessage<::HSS::Times::WTimeZone_TZTimeZone>(Arena*);
template<> TIMES_API ::HSS::Times::WTimeZone_WTZDetails* Arena::CreateMaybeMessage<::HSS::Times::WTimeZone_WTZDetails>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace HSS {
namespace Times {

// ===================================================================

class TIMES_API WTime PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:HSS.Times.WTime) */ {
 public:
  inline WTime() : WTime(nullptr) {}
  virtual ~WTime();

  WTime(const WTime& from);
  WTime(WTime&& from) noexcept
    : WTime() {
    *this = ::std::move(from);
  }

  inline WTime& operator=(const WTime& from) {
    CopyFrom(from);
    return *this;
  }
  inline WTime& operator=(WTime&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const WTime& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const WTime* internal_default_instance() {
    return reinterpret_cast<const WTime*>(
               &_WTime_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(WTime& a, WTime& b) {
    a.Swap(&b);
  }
  inline void Swap(WTime* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WTime* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline WTime* New() const final {
    return CreateMaybeMessage<WTime>(nullptr);
  }

  WTime* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<WTime>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const WTime& from);
  void MergeFrom(const WTime& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WTime* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "HSS.Times.WTime";
  }
  protected:
  explicit WTime(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_wtime_2eproto);
    return ::descriptor_table_wtime_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTimeFieldNumber = 1,
    kDaylightFieldNumber = 2,
    kTimezoneFieldNumber = 3,
    kTimezoneIdFieldNumber = 4,
  };
  // string time = 1;
  void clear_time();
  const std::string& time() const;
  void set_time(const std::string& value);
  void set_time(std::string&& value);
  void set_time(const char* value);
  void set_time(const char* value, size_t size);
  std::string* mutable_time();
  std::string* release_time();
  void set_allocated_time(std::string* time);
  private:
  const std::string& _internal_time() const;
  void _internal_set_time(const std::string& value);
  std::string* _internal_mutable_time();
  public:

  // .google.protobuf.StringValue daylight = 2;
  bool has_daylight() const;
  private:
  bool _internal_has_daylight() const;
  public:
  void clear_daylight();
  const PROTOBUF_NAMESPACE_ID::StringValue& daylight() const;
  PROTOBUF_NAMESPACE_ID::StringValue* release_daylight();
  PROTOBUF_NAMESPACE_ID::StringValue* mutable_daylight();
  void set_allocated_daylight(PROTOBUF_NAMESPACE_ID::StringValue* daylight);
  private:
  const PROTOBUF_NAMESPACE_ID::StringValue& _internal_daylight() const;
  PROTOBUF_NAMESPACE_ID::StringValue* _internal_mutable_daylight();
  public:
  void unsafe_arena_set_allocated_daylight(
      PROTOBUF_NAMESPACE_ID::StringValue* daylight);
  PROTOBUF_NAMESPACE_ID::StringValue* unsafe_arena_release_daylight();

  // .google.protobuf.StringValue timezone = 3;
  bool has_timezone() const;
  private:
  bool _internal_has_timezone() const;
  public:
  void clear_timezone();
  const PROTOBUF_NAMESPACE_ID::StringValue& timezone() const;
  PROTOBUF_NAMESPACE_ID::StringValue* release_timezone();
  PROTOBUF_NAMESPACE_ID::StringValue* mutable_timezone();
  void set_allocated_timezone(PROTOBUF_NAMESPACE_ID::StringValue* timezone);
  private:
  const PROTOBUF_NAMESPACE_ID::StringValue& _internal_timezone() const;
  PROTOBUF_NAMESPACE_ID::StringValue* _internal_mutable_timezone();
  public:
  void unsafe_arena_set_allocated_timezone(
      PROTOBUF_NAMESPACE_ID::StringValue* timezone);
  PROTOBUF_NAMESPACE_ID::StringValue* unsafe_arena_release_timezone();

  // .google.protobuf.Int32Value timezone_id = 4 [deprecated = true];
  PROTOBUF_DEPRECATED bool has_timezone_id() const;
  private:
  bool _internal_has_timezone_id() const;
  public:
  PROTOBUF_DEPRECATED void clear_timezone_id();
  PROTOBUF_DEPRECATED const PROTOBUF_NAMESPACE_ID::Int32Value& timezone_id() const;
  PROTOBUF_DEPRECATED PROTOBUF_NAMESPACE_ID::Int32Value* release_timezone_id();
  PROTOBUF_DEPRECATED PROTOBUF_NAMESPACE_ID::Int32Value* mutable_timezone_id();
  PROTOBUF_DEPRECATED void set_allocated_timezone_id(PROTOBUF_NAMESPACE_ID::Int32Value* timezone_id);
  private:
  const PROTOBUF_NAMESPACE_ID::Int32Value& _internal_timezone_id() const;
  PROTOBUF_NAMESPACE_ID::Int32Value* _internal_mutable_timezone_id();
  public:
  PROTOBUF_DEPRECATED void unsafe_arena_set_allocated_timezone_id(
      PROTOBUF_NAMESPACE_ID::Int32Value* timezone_id);
  PROTOBUF_DEPRECATED PROTOBUF_NAMESPACE_ID::Int32Value* unsafe_arena_release_timezone_id();

  // @@protoc_insertion_point(class_scope:HSS.Times.WTime)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr time_;
  PROTOBUF_NAMESPACE_ID::StringValue* daylight_;
  PROTOBUF_NAMESPACE_ID::StringValue* timezone_;
  PROTOBUF_NAMESPACE_ID::Int32Value* timezone_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_wtime_2eproto;
};
// -------------------------------------------------------------------

class TIMES_API WTimeSpan PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:HSS.Times.WTimeSpan) */ {
 public:
  inline WTimeSpan() : WTimeSpan(nullptr) {}
  virtual ~WTimeSpan();

  WTimeSpan(const WTimeSpan& from);
  WTimeSpan(WTimeSpan&& from) noexcept
    : WTimeSpan() {
    *this = ::std::move(from);
  }

  inline WTimeSpan& operator=(const WTimeSpan& from) {
    CopyFrom(from);
    return *this;
  }
  inline WTimeSpan& operator=(WTimeSpan&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const WTimeSpan& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const WTimeSpan* internal_default_instance() {
    return reinterpret_cast<const WTimeSpan*>(
               &_WTimeSpan_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(WTimeSpan& a, WTimeSpan& b) {
    a.Swap(&b);
  }
  inline void Swap(WTimeSpan* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WTimeSpan* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline WTimeSpan* New() const final {
    return CreateMaybeMessage<WTimeSpan>(nullptr);
  }

  WTimeSpan* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<WTimeSpan>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const WTimeSpan& from);
  void MergeFrom(const WTimeSpan& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WTimeSpan* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "HSS.Times.WTimeSpan";
  }
  protected:
  explicit WTimeSpan(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_wtime_2eproto);
    return ::descriptor_table_wtime_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTimeFieldNumber = 1,
  };
  // string time = 1;
  void clear_time();
  const std::string& time() const;
  void set_time(const std::string& value);
  void set_time(std::string&& value);
  void set_time(const char* value);
  void set_time(const char* value, size_t size);
  std::string* mutable_time();
  std::string* release_time();
  void set_allocated_time(std::string* time);
  private:
  const std::string& _internal_time() const;
  void _internal_set_time(const std::string& value);
  std::string* _internal_mutable_time();
  public:

  // @@protoc_insertion_point(class_scope:HSS.Times.WTimeSpan)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr time_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_wtime_2eproto;
};
// -------------------------------------------------------------------

class TIMES_API WTimeZone_WTZDetails PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:HSS.Times.WTimeZone.WTZDetails) */ {
 public:
  inline WTimeZone_WTZDetails() : WTimeZone_WTZDetails(nullptr) {}
  virtual ~WTimeZone_WTZDetails();

  WTimeZone_WTZDetails(const WTimeZone_WTZDetails& from);
  WTimeZone_WTZDetails(WTimeZone_WTZDetails&& from) noexcept
    : WTimeZone_WTZDetails() {
    *this = ::std::move(from);
  }

  inline WTimeZone_WTZDetails& operator=(const WTimeZone_WTZDetails& from) {
    CopyFrom(from);
    return *this;
  }
  inline WTimeZone_WTZDetails& operator=(WTimeZone_WTZDetails&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const WTimeZone_WTZDetails& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const WTimeZone_WTZDetails* internal_default_instance() {
    return reinterpret_cast<const WTimeZone_WTZDetails*>(
               &_WTimeZone_WTZDetails_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(WTimeZone_WTZDetails& a, WTimeZone_WTZDetails& b) {
    a.Swap(&b);
  }
  inline void Swap(WTimeZone_WTZDetails* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WTimeZone_WTZDetails* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline WTimeZone_WTZDetails* New() const final {
    return CreateMaybeMessage<WTimeZone_WTZDetails>(nullptr);
  }

  WTimeZone_WTZDetails* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<WTimeZone_WTZDetails>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const WTimeZone_WTZDetails& from);
  void MergeFrom(const WTimeZone_WTZDetails& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WTimeZone_WTZDetails* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "HSS.Times.WTimeZone.WTZDetails";
  }
  protected:
  explicit WTimeZone_WTZDetails(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_wtime_2eproto);
    return ::descriptor_table_wtime_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAmtTimeZoneFieldNumber = 1,
    kStartDSTFieldNumber = 2,
    kEndDSTFieldNumber = 3,
    kAmtDSTFieldNumber = 4,
  };
  // .HSS.Times.WTimeSpan amtTimeZone = 1;
  bool has_amttimezone() const;
  private:
  bool _internal_has_amttimezone() const;
  public:
  void clear_amttimezone();
  const ::HSS::Times::WTimeSpan& amttimezone() const;
  ::HSS::Times::WTimeSpan* release_amttimezone();
  ::HSS::Times::WTimeSpan* mutable_amttimezone();
  void set_allocated_amttimezone(::HSS::Times::WTimeSpan* amttimezone);
  private:
  const ::HSS::Times::WTimeSpan& _internal_amttimezone() const;
  ::HSS::Times::WTimeSpan* _internal_mutable_amttimezone();
  public:
  void unsafe_arena_set_allocated_amttimezone(
      ::HSS::Times::WTimeSpan* amttimezone);
  ::HSS::Times::WTimeSpan* unsafe_arena_release_amttimezone();

  // .HSS.Times.WTimeSpan startDST = 2;
  bool has_startdst() const;
  private:
  bool _internal_has_startdst() const;
  public:
  void clear_startdst();
  const ::HSS::Times::WTimeSpan& startdst() const;
  ::HSS::Times::WTimeSpan* release_startdst();
  ::HSS::Times::WTimeSpan* mutable_startdst();
  void set_allocated_startdst(::HSS::Times::WTimeSpan* startdst);
  private:
  const ::HSS::Times::WTimeSpan& _internal_startdst() const;
  ::HSS::Times::WTimeSpan* _internal_mutable_startdst();
  public:
  void unsafe_arena_set_allocated_startdst(
      ::HSS::Times::WTimeSpan* startdst);
  ::HSS::Times::WTimeSpan* unsafe_arena_release_startdst();

  // .HSS.Times.WTimeSpan endDST = 3;
  bool has_enddst() const;
  private:
  bool _internal_has_enddst() const;
  public:
  void clear_enddst();
  const ::HSS::Times::WTimeSpan& enddst() const;
  ::HSS::Times::WTimeSpan* release_enddst();
  ::HSS::Times::WTimeSpan* mutable_enddst();
  void set_allocated_enddst(::HSS::Times::WTimeSpan* enddst);
  private:
  const ::HSS::Times::WTimeSpan& _internal_enddst() const;
  ::HSS::Times::WTimeSpan* _internal_mutable_enddst();
  public:
  void unsafe_arena_set_allocated_enddst(
      ::HSS::Times::WTimeSpan* enddst);
  ::HSS::Times::WTimeSpan* unsafe_arena_release_enddst();

  // .HSS.Times.WTimeSpan amtDST = 4;
  bool has_amtdst() const;
  private:
  bool _internal_has_amtdst() const;
  public:
  void clear_amtdst();
  const ::HSS::Times::WTimeSpan& amtdst() const;
  ::HSS::Times::WTimeSpan* release_amtdst();
  ::HSS::Times::WTimeSpan* mutable_amtdst();
  void set_allocated_amtdst(::HSS::Times::WTimeSpan* amtdst);
  private:
  const ::HSS::Times::WTimeSpan& _internal_amtdst() const;
  ::HSS::Times::WTimeSpan* _internal_mutable_amtdst();
  public:
  void unsafe_arena_set_allocated_amtdst(
      ::HSS::Times::WTimeSpan* amtdst);
  ::HSS::Times::WTimeSpan* unsafe_arena_release_amtdst();

  // @@protoc_insertion_point(class_scope:HSS.Times.WTimeZone.WTZDetails)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::HSS::Times::WTimeSpan* amttimezone_;
  ::HSS::Times::WTimeSpan* startdst_;
  ::HSS::Times::WTimeSpan* enddst_;
  ::HSS::Times::WTimeSpan* amtdst_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_wtime_2eproto;
};
// -------------------------------------------------------------------

class TIMES_API WTimeZone_TZTimeZone PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:HSS.Times.WTimeZone.TZTimeZone) */ {
 public:
  inline WTimeZone_TZTimeZone() : WTimeZone_TZTimeZone(nullptr) {}
  virtual ~WTimeZone_TZTimeZone();

  WTimeZone_TZTimeZone(const WTimeZone_TZTimeZone& from);
  WTimeZone_TZTimeZone(WTimeZone_TZTimeZone&& from) noexcept
    : WTimeZone_TZTimeZone() {
    *this = ::std::move(from);
  }

  inline WTimeZone_TZTimeZone& operator=(const WTimeZone_TZTimeZone& from) {
    CopyFrom(from);
    return *this;
  }
  inline WTimeZone_TZTimeZone& operator=(WTimeZone_TZTimeZone&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const WTimeZone_TZTimeZone& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const WTimeZone_TZTimeZone* internal_default_instance() {
    return reinterpret_cast<const WTimeZone_TZTimeZone*>(
               &_WTimeZone_TZTimeZone_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(WTimeZone_TZTimeZone& a, WTimeZone_TZTimeZone& b) {
    a.Swap(&b);
  }
  inline void Swap(WTimeZone_TZTimeZone* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WTimeZone_TZTimeZone* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline WTimeZone_TZTimeZone* New() const final {
    return CreateMaybeMessage<WTimeZone_TZTimeZone>(nullptr);
  }

  WTimeZone_TZTimeZone* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<WTimeZone_TZTimeZone>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const WTimeZone_TZTimeZone& from);
  void MergeFrom(const WTimeZone_TZTimeZone& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WTimeZone_TZTimeZone* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "HSS.Times.WTimeZone.TZTimeZone";
  }
  protected:
  explicit WTimeZone_TZTimeZone(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_wtime_2eproto);
    return ::descriptor_table_wtime_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kDaylightFieldNumber = 2,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // bool daylight = 2;
  bool has_daylight() const;
  private:
  bool _internal_has_daylight() const;
  public:
  void clear_daylight();
  bool daylight() const;
  void set_daylight(bool value);
  private:
  bool _internal_daylight() const;
  void _internal_set_daylight(bool value);
  public:

  // @@protoc_insertion_point(class_scope:HSS.Times.WTimeZone.TZTimeZone)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  bool daylight_;
  friend struct ::TableStruct_wtime_2eproto;
};
// -------------------------------------------------------------------

class TIMES_API WTimeZone PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:HSS.Times.WTimeZone) */ {
 public:
  inline WTimeZone() : WTimeZone(nullptr) {}
  virtual ~WTimeZone();

  WTimeZone(const WTimeZone& from);
  WTimeZone(WTimeZone&& from) noexcept
    : WTimeZone() {
    *this = ::std::move(from);
  }

  inline WTimeZone& operator=(const WTimeZone& from) {
    CopyFrom(from);
    return *this;
  }
  inline WTimeZone& operator=(WTimeZone&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const WTimeZone& default_instance();

  enum MsgCase {
    kTimezoneIndex = 2,
    kTimezoneDetails = 3,
    kTztimezone = 4,
    MSG_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const WTimeZone* internal_default_instance() {
    return reinterpret_cast<const WTimeZone*>(
               &_WTimeZone_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(WTimeZone& a, WTimeZone& b) {
    a.Swap(&b);
  }
  inline void Swap(WTimeZone* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WTimeZone* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline WTimeZone* New() const final {
    return CreateMaybeMessage<WTimeZone>(nullptr);
  }

  WTimeZone* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<WTimeZone>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const WTimeZone& from);
  void MergeFrom(const WTimeZone& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WTimeZone* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "HSS.Times.WTimeZone";
  }
  protected:
  explicit WTimeZone(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_wtime_2eproto);
    return ::descriptor_table_wtime_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef WTimeZone_WTZDetails WTZDetails;
  typedef WTimeZone_TZTimeZone TZTimeZone;

  // accessors -------------------------------------------------------

  enum : int {
    kVersionFieldNumber = 1,
    kTimezoneIndexFieldNumber = 2,
    kTimezoneDetailsFieldNumber = 3,
    kTztimezoneFieldNumber = 4,
  };
  // int32 version = 1;
  void clear_version();
  ::PROTOBUF_NAMESPACE_ID::int32 version() const;
  void set_version(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_version() const;
  void _internal_set_version(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 timezoneIndex = 2;
  private:
  bool _internal_has_timezoneindex() const;
  public:
  void clear_timezoneindex();
  ::PROTOBUF_NAMESPACE_ID::int32 timezoneindex() const;
  void set_timezoneindex(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_timezoneindex() const;
  void _internal_set_timezoneindex(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // .HSS.Times.WTimeZone.WTZDetails timezoneDetails = 3 [deprecated = true];
  PROTOBUF_DEPRECATED bool has_timezonedetails() const;
  private:
  bool _internal_has_timezonedetails() const;
  public:
  PROTOBUF_DEPRECATED void clear_timezonedetails();
  PROTOBUF_DEPRECATED const ::HSS::Times::WTimeZone_WTZDetails& timezonedetails() const;
  PROTOBUF_DEPRECATED ::HSS::Times::WTimeZone_WTZDetails* release_timezonedetails();
  PROTOBUF_DEPRECATED ::HSS::Times::WTimeZone_WTZDetails* mutable_timezonedetails();
  PROTOBUF_DEPRECATED void set_allocated_timezonedetails(::HSS::Times::WTimeZone_WTZDetails* timezonedetails);
  private:
  const ::HSS::Times::WTimeZone_WTZDetails& _internal_timezonedetails() const;
  ::HSS::Times::WTimeZone_WTZDetails* _internal_mutable_timezonedetails();
  public:
  PROTOBUF_DEPRECATED void unsafe_arena_set_allocated_timezonedetails(
      ::HSS::Times::WTimeZone_WTZDetails* timezonedetails);
  PROTOBUF_DEPRECATED ::HSS::Times::WTimeZone_WTZDetails* unsafe_arena_release_timezonedetails();

  // .HSS.Times.WTimeZone.TZTimeZone tztimezone = 4;
  bool has_tztimezone() const;
  private:
  bool _internal_has_tztimezone() const;
  public:
  void clear_tztimezone();
  const ::HSS::Times::WTimeZone_TZTimeZone& tztimezone() const;
  ::HSS::Times::WTimeZone_TZTimeZone* release_tztimezone();
  ::HSS::Times::WTimeZone_TZTimeZone* mutable_tztimezone();
  void set_allocated_tztimezone(::HSS::Times::WTimeZone_TZTimeZone* tztimezone);
  private:
  const ::HSS::Times::WTimeZone_TZTimeZone& _internal_tztimezone() const;
  ::HSS::Times::WTimeZone_TZTimeZone* _internal_mutable_tztimezone();
  public:
  void unsafe_arena_set_allocated_tztimezone(
      ::HSS::Times::WTimeZone_TZTimeZone* tztimezone);
  ::HSS::Times::WTimeZone_TZTimeZone* unsafe_arena_release_tztimezone();

  void clear_msg();
  MsgCase msg_case() const;
  // @@protoc_insertion_point(class_scope:HSS.Times.WTimeZone)
 private:
  class _Internal;
  void set_has_timezoneindex();
  void set_has_timezonedetails();
  void set_has_tztimezone();

  inline bool has_msg() const;
  inline void clear_has_msg();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int32 version_;
  union MsgUnion {
    MsgUnion() {}
    ::PROTOBUF_NAMESPACE_ID::int32 timezoneindex_;
    ::HSS::Times::WTimeZone_WTZDetails* timezonedetails_;
    ::HSS::Times::WTimeZone_TZTimeZone* tztimezone_;
  } msg_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint32 _oneof_case_[1];

  friend struct ::TableStruct_wtime_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// WTime

// string time = 1;
inline void WTime::clear_time() {
  time_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& WTime::time() const {
  // @@protoc_insertion_point(field_get:HSS.Times.WTime.time)
  return _internal_time();
}
inline void WTime::set_time(const std::string& value) {
  _internal_set_time(value);
  // @@protoc_insertion_point(field_set:HSS.Times.WTime.time)
}
inline std::string* WTime::mutable_time() {
  // @@protoc_insertion_point(field_mutable:HSS.Times.WTime.time)
  return _internal_mutable_time();
}
inline const std::string& WTime::_internal_time() const {
  return time_.Get();
}
inline void WTime::_internal_set_time(const std::string& value) {
  
  time_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void WTime::set_time(std::string&& value) {
  
  time_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:HSS.Times.WTime.time)
}
inline void WTime::set_time(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  time_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:HSS.Times.WTime.time)
}
inline void WTime::set_time(const char* value,
    size_t size) {
  
  time_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:HSS.Times.WTime.time)
}
inline std::string* WTime::_internal_mutable_time() {
  
  return time_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* WTime::release_time() {
  // @@protoc_insertion_point(field_release:HSS.Times.WTime.time)
  return time_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void WTime::set_allocated_time(std::string* time) {
  if (time != nullptr) {
    
  } else {
    
  }
  time_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), time,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:HSS.Times.WTime.time)
}

// .google.protobuf.StringValue daylight = 2;
inline bool WTime::_internal_has_daylight() const {
  return this != internal_default_instance() && daylight_ != nullptr;
}
inline bool WTime::has_daylight() const {
  return _internal_has_daylight();
}
inline const PROTOBUF_NAMESPACE_ID::StringValue& WTime::_internal_daylight() const {
  const PROTOBUF_NAMESPACE_ID::StringValue* p = daylight_;
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::StringValue*>(
      &PROTOBUF_NAMESPACE_ID::_StringValue_default_instance_);
}
inline const PROTOBUF_NAMESPACE_ID::StringValue& WTime::daylight() const {
  // @@protoc_insertion_point(field_get:HSS.Times.WTime.daylight)
  return _internal_daylight();
}
inline void WTime::unsafe_arena_set_allocated_daylight(
    PROTOBUF_NAMESPACE_ID::StringValue* daylight) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(daylight_);
  }
  daylight_ = daylight;
  if (daylight) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:HSS.Times.WTime.daylight)
}
inline PROTOBUF_NAMESPACE_ID::StringValue* WTime::release_daylight() {
  
  PROTOBUF_NAMESPACE_ID::StringValue* temp = daylight_;
  daylight_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::StringValue* WTime::unsafe_arena_release_daylight() {
  // @@protoc_insertion_point(field_release:HSS.Times.WTime.daylight)
  
  PROTOBUF_NAMESPACE_ID::StringValue* temp = daylight_;
  daylight_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::StringValue* WTime::_internal_mutable_daylight() {
  
  if (daylight_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::StringValue>(GetArena());
    daylight_ = p;
  }
  return daylight_;
}
inline PROTOBUF_NAMESPACE_ID::StringValue* WTime::mutable_daylight() {
  // @@protoc_insertion_point(field_mutable:HSS.Times.WTime.daylight)
  return _internal_mutable_daylight();
}
inline void WTime::set_allocated_daylight(PROTOBUF_NAMESPACE_ID::StringValue* daylight) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(daylight_);
  }
  if (daylight) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(daylight)->GetArena();
    if (message_arena != submessage_arena) {
      daylight = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, daylight, submessage_arena);
    }
    
  } else {
    
  }
  daylight_ = daylight;
  // @@protoc_insertion_point(field_set_allocated:HSS.Times.WTime.daylight)
}

// .google.protobuf.StringValue timezone = 3;
inline bool WTime::_internal_has_timezone() const {
  return this != internal_default_instance() && timezone_ != nullptr;
}
inline bool WTime::has_timezone() const {
  return _internal_has_timezone();
}
inline const PROTOBUF_NAMESPACE_ID::StringValue& WTime::_internal_timezone() const {
  const PROTOBUF_NAMESPACE_ID::StringValue* p = timezone_;
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::StringValue*>(
      &PROTOBUF_NAMESPACE_ID::_StringValue_default_instance_);
}
inline const PROTOBUF_NAMESPACE_ID::StringValue& WTime::timezone() const {
  // @@protoc_insertion_point(field_get:HSS.Times.WTime.timezone)
  return _internal_timezone();
}
inline void WTime::unsafe_arena_set_allocated_timezone(
    PROTOBUF_NAMESPACE_ID::StringValue* timezone) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timezone_);
  }
  timezone_ = timezone;
  if (timezone) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:HSS.Times.WTime.timezone)
}
inline PROTOBUF_NAMESPACE_ID::StringValue* WTime::release_timezone() {
  
  PROTOBUF_NAMESPACE_ID::StringValue* temp = timezone_;
  timezone_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::StringValue* WTime::unsafe_arena_release_timezone() {
  // @@protoc_insertion_point(field_release:HSS.Times.WTime.timezone)
  
  PROTOBUF_NAMESPACE_ID::StringValue* temp = timezone_;
  timezone_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::StringValue* WTime::_internal_mutable_timezone() {
  
  if (timezone_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::StringValue>(GetArena());
    timezone_ = p;
  }
  return timezone_;
}
inline PROTOBUF_NAMESPACE_ID::StringValue* WTime::mutable_timezone() {
  // @@protoc_insertion_point(field_mutable:HSS.Times.WTime.timezone)
  return _internal_mutable_timezone();
}
inline void WTime::set_allocated_timezone(PROTOBUF_NAMESPACE_ID::StringValue* timezone) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(timezone_);
  }
  if (timezone) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timezone)->GetArena();
    if (message_arena != submessage_arena) {
      timezone = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, timezone, submessage_arena);
    }
    
  } else {
    
  }
  timezone_ = timezone;
  // @@protoc_insertion_point(field_set_allocated:HSS.Times.WTime.timezone)
}

// .google.protobuf.Int32Value timezone_id = 4 [deprecated = true];
inline bool WTime::_internal_has_timezone_id() const {
  return this != internal_default_instance() && timezone_id_ != nullptr;
}
inline bool WTime::has_timezone_id() const {
  return _internal_has_timezone_id();
}
inline const PROTOBUF_NAMESPACE_ID::Int32Value& WTime::_internal_timezone_id() const {
  const PROTOBUF_NAMESPACE_ID::Int32Value* p = timezone_id_;
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::Int32Value*>(
      &PROTOBUF_NAMESPACE_ID::_Int32Value_default_instance_);
}
inline const PROTOBUF_NAMESPACE_ID::Int32Value& WTime::timezone_id() const {
  // @@protoc_insertion_point(field_get:HSS.Times.WTime.timezone_id)
  return _internal_timezone_id();
}
inline void WTime::unsafe_arena_set_allocated_timezone_id(
    PROTOBUF_NAMESPACE_ID::Int32Value* timezone_id) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timezone_id_);
  }
  timezone_id_ = timezone_id;
  if (timezone_id) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:HSS.Times.WTime.timezone_id)
}
inline PROTOBUF_NAMESPACE_ID::Int32Value* WTime::release_timezone_id() {
  
  PROTOBUF_NAMESPACE_ID::Int32Value* temp = timezone_id_;
  timezone_id_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Int32Value* WTime::unsafe_arena_release_timezone_id() {
  // @@protoc_insertion_point(field_release:HSS.Times.WTime.timezone_id)
  
  PROTOBUF_NAMESPACE_ID::Int32Value* temp = timezone_id_;
  timezone_id_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Int32Value* WTime::_internal_mutable_timezone_id() {
  
  if (timezone_id_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::Int32Value>(GetArena());
    timezone_id_ = p;
  }
  return timezone_id_;
}
inline PROTOBUF_NAMESPACE_ID::Int32Value* WTime::mutable_timezone_id() {
  // @@protoc_insertion_point(field_mutable:HSS.Times.WTime.timezone_id)
  return _internal_mutable_timezone_id();
}
inline void WTime::set_allocated_timezone_id(PROTOBUF_NAMESPACE_ID::Int32Value* timezone_id) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(timezone_id_);
  }
  if (timezone_id) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timezone_id)->GetArena();
    if (message_arena != submessage_arena) {
      timezone_id = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, timezone_id, submessage_arena);
    }
    
  } else {
    
  }
  timezone_id_ = timezone_id;
  // @@protoc_insertion_point(field_set_allocated:HSS.Times.WTime.timezone_id)
}

// -------------------------------------------------------------------

// WTimeSpan

// string time = 1;
inline void WTimeSpan::clear_time() {
  time_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& WTimeSpan::time() const {
  // @@protoc_insertion_point(field_get:HSS.Times.WTimeSpan.time)
  return _internal_time();
}
inline void WTimeSpan::set_time(const std::string& value) {
  _internal_set_time(value);
  // @@protoc_insertion_point(field_set:HSS.Times.WTimeSpan.time)
}
inline std::string* WTimeSpan::mutable_time() {
  // @@protoc_insertion_point(field_mutable:HSS.Times.WTimeSpan.time)
  return _internal_mutable_time();
}
inline const std::string& WTimeSpan::_internal_time() const {
  return time_.Get();
}
inline void WTimeSpan::_internal_set_time(const std::string& value) {
  
  time_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void WTimeSpan::set_time(std::string&& value) {
  
  time_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:HSS.Times.WTimeSpan.time)
}
inline void WTimeSpan::set_time(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  time_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:HSS.Times.WTimeSpan.time)
}
inline void WTimeSpan::set_time(const char* value,
    size_t size) {
  
  time_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:HSS.Times.WTimeSpan.time)
}
inline std::string* WTimeSpan::_internal_mutable_time() {
  
  return time_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* WTimeSpan::release_time() {
  // @@protoc_insertion_point(field_release:HSS.Times.WTimeSpan.time)
  return time_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void WTimeSpan::set_allocated_time(std::string* time) {
  if (time != nullptr) {
    
  } else {
    
  }
  time_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), time,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:HSS.Times.WTimeSpan.time)
}

// -------------------------------------------------------------------

// WTimeZone_WTZDetails

// .HSS.Times.WTimeSpan amtTimeZone = 1;
inline bool WTimeZone_WTZDetails::_internal_has_amttimezone() const {
  return this != internal_default_instance() && amttimezone_ != nullptr;
}
inline bool WTimeZone_WTZDetails::has_amttimezone() const {
  return _internal_has_amttimezone();
}
inline void WTimeZone_WTZDetails::clear_amttimezone() {
  if (GetArena() == nullptr && amttimezone_ != nullptr) {
    delete amttimezone_;
  }
  amttimezone_ = nullptr;
}
inline const ::HSS::Times::WTimeSpan& WTimeZone_WTZDetails::_internal_amttimezone() const {
  const ::HSS::Times::WTimeSpan* p = amttimezone_;
  return p != nullptr ? *p : *reinterpret_cast<const ::HSS::Times::WTimeSpan*>(
      &::HSS::Times::_WTimeSpan_default_instance_);
}
inline const ::HSS::Times::WTimeSpan& WTimeZone_WTZDetails::amttimezone() const {
  // @@protoc_insertion_point(field_get:HSS.Times.WTimeZone.WTZDetails.amtTimeZone)
  return _internal_amttimezone();
}
inline void WTimeZone_WTZDetails::unsafe_arena_set_allocated_amttimezone(
    ::HSS::Times::WTimeSpan* amttimezone) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(amttimezone_);
  }
  amttimezone_ = amttimezone;
  if (amttimezone) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:HSS.Times.WTimeZone.WTZDetails.amtTimeZone)
}
inline ::HSS::Times::WTimeSpan* WTimeZone_WTZDetails::release_amttimezone() {
  
  ::HSS::Times::WTimeSpan* temp = amttimezone_;
  amttimezone_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::HSS::Times::WTimeSpan* WTimeZone_WTZDetails::unsafe_arena_release_amttimezone() {
  // @@protoc_insertion_point(field_release:HSS.Times.WTimeZone.WTZDetails.amtTimeZone)
  
  ::HSS::Times::WTimeSpan* temp = amttimezone_;
  amttimezone_ = nullptr;
  return temp;
}
inline ::HSS::Times::WTimeSpan* WTimeZone_WTZDetails::_internal_mutable_amttimezone() {
  
  if (amttimezone_ == nullptr) {
    auto* p = CreateMaybeMessage<::HSS::Times::WTimeSpan>(GetArena());
    amttimezone_ = p;
  }
  return amttimezone_;
}
inline ::HSS::Times::WTimeSpan* WTimeZone_WTZDetails::mutable_amttimezone() {
  // @@protoc_insertion_point(field_mutable:HSS.Times.WTimeZone.WTZDetails.amtTimeZone)
  return _internal_mutable_amttimezone();
}
inline void WTimeZone_WTZDetails::set_allocated_amttimezone(::HSS::Times::WTimeSpan* amttimezone) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete amttimezone_;
  }
  if (amttimezone) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(amttimezone);
    if (message_arena != submessage_arena) {
      amttimezone = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, amttimezone, submessage_arena);
    }
    
  } else {
    
  }
  amttimezone_ = amttimezone;
  // @@protoc_insertion_point(field_set_allocated:HSS.Times.WTimeZone.WTZDetails.amtTimeZone)
}

// .HSS.Times.WTimeSpan startDST = 2;
inline bool WTimeZone_WTZDetails::_internal_has_startdst() const {
  return this != internal_default_instance() && startdst_ != nullptr;
}
inline bool WTimeZone_WTZDetails::has_startdst() const {
  return _internal_has_startdst();
}
inline void WTimeZone_WTZDetails::clear_startdst() {
  if (GetArena() == nullptr && startdst_ != nullptr) {
    delete startdst_;
  }
  startdst_ = nullptr;
}
inline const ::HSS::Times::WTimeSpan& WTimeZone_WTZDetails::_internal_startdst() const {
  const ::HSS::Times::WTimeSpan* p = startdst_;
  return p != nullptr ? *p : *reinterpret_cast<const ::HSS::Times::WTimeSpan*>(
      &::HSS::Times::_WTimeSpan_default_instance_);
}
inline const ::HSS::Times::WTimeSpan& WTimeZone_WTZDetails::startdst() const {
  // @@protoc_insertion_point(field_get:HSS.Times.WTimeZone.WTZDetails.startDST)
  return _internal_startdst();
}
inline void WTimeZone_WTZDetails::unsafe_arena_set_allocated_startdst(
    ::HSS::Times::WTimeSpan* startdst) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(startdst_);
  }
  startdst_ = startdst;
  if (startdst) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:HSS.Times.WTimeZone.WTZDetails.startDST)
}
inline ::HSS::Times::WTimeSpan* WTimeZone_WTZDetails::release_startdst() {
  
  ::HSS::Times::WTimeSpan* temp = startdst_;
  startdst_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::HSS::Times::WTimeSpan* WTimeZone_WTZDetails::unsafe_arena_release_startdst() {
  // @@protoc_insertion_point(field_release:HSS.Times.WTimeZone.WTZDetails.startDST)
  
  ::HSS::Times::WTimeSpan* temp = startdst_;
  startdst_ = nullptr;
  return temp;
}
inline ::HSS::Times::WTimeSpan* WTimeZone_WTZDetails::_internal_mutable_startdst() {
  
  if (startdst_ == nullptr) {
    auto* p = CreateMaybeMessage<::HSS::Times::WTimeSpan>(GetArena());
    startdst_ = p;
  }
  return startdst_;
}
inline ::HSS::Times::WTimeSpan* WTimeZone_WTZDetails::mutable_startdst() {
  // @@protoc_insertion_point(field_mutable:HSS.Times.WTimeZone.WTZDetails.startDST)
  return _internal_mutable_startdst();
}
inline void WTimeZone_WTZDetails::set_allocated_startdst(::HSS::Times::WTimeSpan* startdst) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete startdst_;
  }
  if (startdst) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(startdst);
    if (message_arena != submessage_arena) {
      startdst = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, startdst, submessage_arena);
    }
    
  } else {
    
  }
  startdst_ = startdst;
  // @@protoc_insertion_point(field_set_allocated:HSS.Times.WTimeZone.WTZDetails.startDST)
}

// .HSS.Times.WTimeSpan endDST = 3;
inline bool WTimeZone_WTZDetails::_internal_has_enddst() const {
  return this != internal_default_instance() && enddst_ != nullptr;
}
inline bool WTimeZone_WTZDetails::has_enddst() const {
  return _internal_has_enddst();
}
inline void WTimeZone_WTZDetails::clear_enddst() {
  if (GetArena() == nullptr && enddst_ != nullptr) {
    delete enddst_;
  }
  enddst_ = nullptr;
}
inline const ::HSS::Times::WTimeSpan& WTimeZone_WTZDetails::_internal_enddst() const {
  const ::HSS::Times::WTimeSpan* p = enddst_;
  return p != nullptr ? *p : *reinterpret_cast<const ::HSS::Times::WTimeSpan*>(
      &::HSS::Times::_WTimeSpan_default_instance_);
}
inline const ::HSS::Times::WTimeSpan& WTimeZone_WTZDetails::enddst() const {
  // @@protoc_insertion_point(field_get:HSS.Times.WTimeZone.WTZDetails.endDST)
  return _internal_enddst();
}
inline void WTimeZone_WTZDetails::unsafe_arena_set_allocated_enddst(
    ::HSS::Times::WTimeSpan* enddst) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(enddst_);
  }
  enddst_ = enddst;
  if (enddst) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:HSS.Times.WTimeZone.WTZDetails.endDST)
}
inline ::HSS::Times::WTimeSpan* WTimeZone_WTZDetails::release_enddst() {
  
  ::HSS::Times::WTimeSpan* temp = enddst_;
  enddst_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::HSS::Times::WTimeSpan* WTimeZone_WTZDetails::unsafe_arena_release_enddst() {
  // @@protoc_insertion_point(field_release:HSS.Times.WTimeZone.WTZDetails.endDST)
  
  ::HSS::Times::WTimeSpan* temp = enddst_;
  enddst_ = nullptr;
  return temp;
}
inline ::HSS::Times::WTimeSpan* WTimeZone_WTZDetails::_internal_mutable_enddst() {
  
  if (enddst_ == nullptr) {
    auto* p = CreateMaybeMessage<::HSS::Times::WTimeSpan>(GetArena());
    enddst_ = p;
  }
  return enddst_;
}
inline ::HSS::Times::WTimeSpan* WTimeZone_WTZDetails::mutable_enddst() {
  // @@protoc_insertion_point(field_mutable:HSS.Times.WTimeZone.WTZDetails.endDST)
  return _internal_mutable_enddst();
}
inline void WTimeZone_WTZDetails::set_allocated_enddst(::HSS::Times::WTimeSpan* enddst) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete enddst_;
  }
  if (enddst) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(enddst);
    if (message_arena != submessage_arena) {
      enddst = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, enddst, submessage_arena);
    }
    
  } else {
    
  }
  enddst_ = enddst;
  // @@protoc_insertion_point(field_set_allocated:HSS.Times.WTimeZone.WTZDetails.endDST)
}

// .HSS.Times.WTimeSpan amtDST = 4;
inline bool WTimeZone_WTZDetails::_internal_has_amtdst() const {
  return this != internal_default_instance() && amtdst_ != nullptr;
}
inline bool WTimeZone_WTZDetails::has_amtdst() const {
  return _internal_has_amtdst();
}
inline void WTimeZone_WTZDetails::clear_amtdst() {
  if (GetArena() == nullptr && amtdst_ != nullptr) {
    delete amtdst_;
  }
  amtdst_ = nullptr;
}
inline const ::HSS::Times::WTimeSpan& WTimeZone_WTZDetails::_internal_amtdst() const {
  const ::HSS::Times::WTimeSpan* p = amtdst_;
  return p != nullptr ? *p : *reinterpret_cast<const ::HSS::Times::WTimeSpan*>(
      &::HSS::Times::_WTimeSpan_default_instance_);
}
inline const ::HSS::Times::WTimeSpan& WTimeZone_WTZDetails::amtdst() const {
  // @@protoc_insertion_point(field_get:HSS.Times.WTimeZone.WTZDetails.amtDST)
  return _internal_amtdst();
}
inline void WTimeZone_WTZDetails::unsafe_arena_set_allocated_amtdst(
    ::HSS::Times::WTimeSpan* amtdst) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(amtdst_);
  }
  amtdst_ = amtdst;
  if (amtdst) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:HSS.Times.WTimeZone.WTZDetails.amtDST)
}
inline ::HSS::Times::WTimeSpan* WTimeZone_WTZDetails::release_amtdst() {
  
  ::HSS::Times::WTimeSpan* temp = amtdst_;
  amtdst_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::HSS::Times::WTimeSpan* WTimeZone_WTZDetails::unsafe_arena_release_amtdst() {
  // @@protoc_insertion_point(field_release:HSS.Times.WTimeZone.WTZDetails.amtDST)
  
  ::HSS::Times::WTimeSpan* temp = amtdst_;
  amtdst_ = nullptr;
  return temp;
}
inline ::HSS::Times::WTimeSpan* WTimeZone_WTZDetails::_internal_mutable_amtdst() {
  
  if (amtdst_ == nullptr) {
    auto* p = CreateMaybeMessage<::HSS::Times::WTimeSpan>(GetArena());
    amtdst_ = p;
  }
  return amtdst_;
}
inline ::HSS::Times::WTimeSpan* WTimeZone_WTZDetails::mutable_amtdst() {
  // @@protoc_insertion_point(field_mutable:HSS.Times.WTimeZone.WTZDetails.amtDST)
  return _internal_mutable_amtdst();
}
inline void WTimeZone_WTZDetails::set_allocated_amtdst(::HSS::Times::WTimeSpan* amtdst) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete amtdst_;
  }
  if (amtdst) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(amtdst);
    if (message_arena != submessage_arena) {
      amtdst = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, amtdst, submessage_arena);
    }
    
  } else {
    
  }
  amtdst_ = amtdst;
  // @@protoc_insertion_point(field_set_allocated:HSS.Times.WTimeZone.WTZDetails.amtDST)
}

// -------------------------------------------------------------------

// WTimeZone_TZTimeZone

// string name = 1;
inline void WTimeZone_TZTimeZone::clear_name() {
  name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& WTimeZone_TZTimeZone::name() const {
  // @@protoc_insertion_point(field_get:HSS.Times.WTimeZone.TZTimeZone.name)
  return _internal_name();
}
inline void WTimeZone_TZTimeZone::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:HSS.Times.WTimeZone.TZTimeZone.name)
}
inline std::string* WTimeZone_TZTimeZone::mutable_name() {
  // @@protoc_insertion_point(field_mutable:HSS.Times.WTimeZone.TZTimeZone.name)
  return _internal_mutable_name();
}
inline const std::string& WTimeZone_TZTimeZone::_internal_name() const {
  return name_.Get();
}
inline void WTimeZone_TZTimeZone::_internal_set_name(const std::string& value) {
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void WTimeZone_TZTimeZone::set_name(std::string&& value) {
  
  name_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:HSS.Times.WTimeZone.TZTimeZone.name)
}
inline void WTimeZone_TZTimeZone::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:HSS.Times.WTimeZone.TZTimeZone.name)
}
inline void WTimeZone_TZTimeZone::set_name(const char* value,
    size_t size) {
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:HSS.Times.WTimeZone.TZTimeZone.name)
}
inline std::string* WTimeZone_TZTimeZone::_internal_mutable_name() {
  
  return name_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* WTimeZone_TZTimeZone::release_name() {
  // @@protoc_insertion_point(field_release:HSS.Times.WTimeZone.TZTimeZone.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void WTimeZone_TZTimeZone::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:HSS.Times.WTimeZone.TZTimeZone.name)
}

// bool daylight = 2;
inline bool WTimeZone_TZTimeZone::_internal_has_daylight() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool WTimeZone_TZTimeZone::has_daylight() const {
  return _internal_has_daylight();
}
inline void WTimeZone_TZTimeZone::clear_daylight() {
  daylight_ = false;
  _has_bits_[0] &= ~0x00000001u;
}
inline bool WTimeZone_TZTimeZone::_internal_daylight() const {
  return daylight_;
}
inline bool WTimeZone_TZTimeZone::daylight() const {
  // @@protoc_insertion_point(field_get:HSS.Times.WTimeZone.TZTimeZone.daylight)
  return _internal_daylight();
}
inline void WTimeZone_TZTimeZone::_internal_set_daylight(bool value) {
  _has_bits_[0] |= 0x00000001u;
  daylight_ = value;
}
inline void WTimeZone_TZTimeZone::set_daylight(bool value) {
  _internal_set_daylight(value);
  // @@protoc_insertion_point(field_set:HSS.Times.WTimeZone.TZTimeZone.daylight)
}

// -------------------------------------------------------------------

// WTimeZone

// int32 version = 1;
inline void WTimeZone::clear_version() {
  version_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 WTimeZone::_internal_version() const {
  return version_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 WTimeZone::version() const {
  // @@protoc_insertion_point(field_get:HSS.Times.WTimeZone.version)
  return _internal_version();
}
inline void WTimeZone::_internal_set_version(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  version_ = value;
}
inline void WTimeZone::set_version(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_version(value);
  // @@protoc_insertion_point(field_set:HSS.Times.WTimeZone.version)
}

// int32 timezoneIndex = 2;
inline bool WTimeZone::_internal_has_timezoneindex() const {
  return msg_case() == kTimezoneIndex;
}
inline void WTimeZone::set_has_timezoneindex() {
  _oneof_case_[0] = kTimezoneIndex;
}
inline void WTimeZone::clear_timezoneindex() {
  if (_internal_has_timezoneindex()) {
    msg_.timezoneindex_ = 0;
    clear_has_msg();
  }
}
inline ::PROTOBUF_NAMESPACE_ID::int32 WTimeZone::_internal_timezoneindex() const {
  if (_internal_has_timezoneindex()) {
    return msg_.timezoneindex_;
  }
  return 0;
}
inline void WTimeZone::_internal_set_timezoneindex(::PROTOBUF_NAMESPACE_ID::int32 value) {
  if (!_internal_has_timezoneindex()) {
    clear_msg();
    set_has_timezoneindex();
  }
  msg_.timezoneindex_ = value;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 WTimeZone::timezoneindex() const {
  // @@protoc_insertion_point(field_get:HSS.Times.WTimeZone.timezoneIndex)
  return _internal_timezoneindex();
}
inline void WTimeZone::set_timezoneindex(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_timezoneindex(value);
  // @@protoc_insertion_point(field_set:HSS.Times.WTimeZone.timezoneIndex)
}

// .HSS.Times.WTimeZone.WTZDetails timezoneDetails = 3 [deprecated = true];
inline bool WTimeZone::_internal_has_timezonedetails() const {
  return msg_case() == kTimezoneDetails;
}
inline bool WTimeZone::has_timezonedetails() const {
  return _internal_has_timezonedetails();
}
inline void WTimeZone::set_has_timezonedetails() {
  _oneof_case_[0] = kTimezoneDetails;
}
inline void WTimeZone::clear_timezonedetails() {
  if (_internal_has_timezonedetails()) {
    if (GetArena() == nullptr) {
      delete msg_.timezonedetails_;
    }
    clear_has_msg();
  }
}
inline ::HSS::Times::WTimeZone_WTZDetails* WTimeZone::release_timezonedetails() {
  // @@protoc_insertion_point(field_release:HSS.Times.WTimeZone.timezoneDetails)
  if (_internal_has_timezonedetails()) {
    clear_has_msg();
      ::HSS::Times::WTimeZone_WTZDetails* temp = msg_.timezonedetails_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    msg_.timezonedetails_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::HSS::Times::WTimeZone_WTZDetails& WTimeZone::_internal_timezonedetails() const {
  return _internal_has_timezonedetails()
      ? *msg_.timezonedetails_
      : *reinterpret_cast< ::HSS::Times::WTimeZone_WTZDetails*>(&::HSS::Times::_WTimeZone_WTZDetails_default_instance_);
}
inline const ::HSS::Times::WTimeZone_WTZDetails& WTimeZone::timezonedetails() const {
  // @@protoc_insertion_point(field_get:HSS.Times.WTimeZone.timezoneDetails)
  return _internal_timezonedetails();
}
inline ::HSS::Times::WTimeZone_WTZDetails* WTimeZone::unsafe_arena_release_timezonedetails() {
  // @@protoc_insertion_point(field_unsafe_arena_release:HSS.Times.WTimeZone.timezoneDetails)
  if (_internal_has_timezonedetails()) {
    clear_has_msg();
    ::HSS::Times::WTimeZone_WTZDetails* temp = msg_.timezonedetails_;
    msg_.timezonedetails_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void WTimeZone::unsafe_arena_set_allocated_timezonedetails(::HSS::Times::WTimeZone_WTZDetails* timezonedetails) {
  clear_msg();
  if (timezonedetails) {
    set_has_timezonedetails();
    msg_.timezonedetails_ = timezonedetails;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:HSS.Times.WTimeZone.timezoneDetails)
}
inline ::HSS::Times::WTimeZone_WTZDetails* WTimeZone::_internal_mutable_timezonedetails() {
  if (!_internal_has_timezonedetails()) {
    clear_msg();
    set_has_timezonedetails();
    msg_.timezonedetails_ = CreateMaybeMessage< ::HSS::Times::WTimeZone_WTZDetails >(GetArena());
  }
  return msg_.timezonedetails_;
}
inline ::HSS::Times::WTimeZone_WTZDetails* WTimeZone::mutable_timezonedetails() {
  // @@protoc_insertion_point(field_mutable:HSS.Times.WTimeZone.timezoneDetails)
  return _internal_mutable_timezonedetails();
}

// .HSS.Times.WTimeZone.TZTimeZone tztimezone = 4;
inline bool WTimeZone::_internal_has_tztimezone() const {
  return msg_case() == kTztimezone;
}
inline bool WTimeZone::has_tztimezone() const {
  return _internal_has_tztimezone();
}
inline void WTimeZone::set_has_tztimezone() {
  _oneof_case_[0] = kTztimezone;
}
inline void WTimeZone::clear_tztimezone() {
  if (_internal_has_tztimezone()) {
    if (GetArena() == nullptr) {
      delete msg_.tztimezone_;
    }
    clear_has_msg();
  }
}
inline ::HSS::Times::WTimeZone_TZTimeZone* WTimeZone::release_tztimezone() {
  // @@protoc_insertion_point(field_release:HSS.Times.WTimeZone.tztimezone)
  if (_internal_has_tztimezone()) {
    clear_has_msg();
      ::HSS::Times::WTimeZone_TZTimeZone* temp = msg_.tztimezone_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    msg_.tztimezone_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::HSS::Times::WTimeZone_TZTimeZone& WTimeZone::_internal_tztimezone() const {
  return _internal_has_tztimezone()
      ? *msg_.tztimezone_
      : *reinterpret_cast< ::HSS::Times::WTimeZone_TZTimeZone*>(&::HSS::Times::_WTimeZone_TZTimeZone_default_instance_);
}
inline const ::HSS::Times::WTimeZone_TZTimeZone& WTimeZone::tztimezone() const {
  // @@protoc_insertion_point(field_get:HSS.Times.WTimeZone.tztimezone)
  return _internal_tztimezone();
}
inline ::HSS::Times::WTimeZone_TZTimeZone* WTimeZone::unsafe_arena_release_tztimezone() {
  // @@protoc_insertion_point(field_unsafe_arena_release:HSS.Times.WTimeZone.tztimezone)
  if (_internal_has_tztimezone()) {
    clear_has_msg();
    ::HSS::Times::WTimeZone_TZTimeZone* temp = msg_.tztimezone_;
    msg_.tztimezone_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void WTimeZone::unsafe_arena_set_allocated_tztimezone(::HSS::Times::WTimeZone_TZTimeZone* tztimezone) {
  clear_msg();
  if (tztimezone) {
    set_has_tztimezone();
    msg_.tztimezone_ = tztimezone;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:HSS.Times.WTimeZone.tztimezone)
}
inline ::HSS::Times::WTimeZone_TZTimeZone* WTimeZone::_internal_mutable_tztimezone() {
  if (!_internal_has_tztimezone()) {
    clear_msg();
    set_has_tztimezone();
    msg_.tztimezone_ = CreateMaybeMessage< ::HSS::Times::WTimeZone_TZTimeZone >(GetArena());
  }
  return msg_.tztimezone_;
}
inline ::HSS::Times::WTimeZone_TZTimeZone* WTimeZone::mutable_tztimezone() {
  // @@protoc_insertion_point(field_mutable:HSS.Times.WTimeZone.tztimezone)
  return _internal_mutable_tztimezone();
}

inline bool WTimeZone::has_msg() const {
  return msg_case() != MSG_NOT_SET;
}
inline void WTimeZone::clear_has_msg() {
  _oneof_case_[0] = MSG_NOT_SET;
}
inline WTimeZone::MsgCase WTimeZone::msg_case() const {
  return WTimeZone::MsgCase(_oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Times
}  // namespace HSS

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_wtime_2eproto
