# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
      - master
    paths:
      - java/**
      - .github/**

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    defaults:
      run:
        working-directory: ./java

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        server-id: github
        cache: 'maven'
        
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.11.1'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build Protobuf
      run: protoc --java_out src/main/java --proto_path ../proto/ wtime.proto
    
    - name: Increment the version number
      id: incVer
      run: |
        mvn validate -DincrementBuild
        mvn versions:commit
        APPLICATION_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add pom.xml
        git commit -m "Update the version" -m "[skip ci]"
        git tag -a v$APPLICATION_VERSION -m "Release v$APPLICATION_VERSION"
        echo "::set-output name=application_version::v$APPLICATION_VERSION"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        tags: true

    - name: Build with Maven
      run: mvn --batch-mode clean compile package
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ steps.incVer.outputs.application_version }}
        files: java/target/WTime.jar
        tag_name: refs/tags/${{ steps.incVer.outputs.application_version }}
        
    - name: Publish package
      run: mvn --batch-mode deploy -X
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
